services:
  discovery-server:
    build: ./infra/discovery-server
    ports:
      - "8761:8761"
    healthcheck:
      test: curl -f http://localhost:8761/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure

  config-server:
    build: ./infra/config-server
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
      SERVER_PORT: 8888
    healthcheck:
      test: curl -f http://localhost:8888/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure

  gateway-server:
    build: ./infra/gateway-server
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
    restart: on-failure

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9092 --list || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure

  init-kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      bash -c "
      kafka-topics --create --if-not-exists --topic stats.user-actions.v1 --partitions 1 --replication-factor 1 --bootstrap-server kafka:9092 &&
      kafka-topics --create --if-not-exists --topic stats.events-similarity.v1 --partitions 1 --replication-factor 1 --bootstrap-server kafka:9092
      "

  ewm-db:
    image: postgres:16.1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ewm-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - ewm-db-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  analyzer-db:
    image: postgres:16.1
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ewm_analyzer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - analyzer-db-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  user-service:
    build: ./core/user-service
    depends_on:
      ewm-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
    restart: on-failure

  event-service:
    build: ./core/event-service
    depends_on:
      ewm-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
    restart: on-failure

  request-service:
    build: ./core/request-service
    depends_on:
      ewm-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
    restart: on-failure

  comment-service:
    build: ./core/comment-service
    depends_on:
      ewm-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
    restart: on-failure

  collector:
    build: ./stats/collector
    depends_on:
      kafka:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    restart: on-failure

  aggregator:
    build: ./stats/aggregator
    depends_on:
      kafka:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    restart: on-failure

  analyzer:
    build: ./stats/analyzer
    depends_on:
      analyzer-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://analyzer-db:5432/ewm_analyzer
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    restart: on-failure

volumes:
  ewm-db-data:
  analyzer-db-data:
