services:
  discovery-server:
    build: ./infra/discovery-server
    ports:
      - "8761:8761"
    healthcheck:
      test: curl -f http://localhost:8761/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure

  config-server:
    build: ./infra/config-server
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
      SERVER_PORT: 8888
    healthcheck:
      test: curl -f http://localhost:8888/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure

  gateway-server:
    build: ./infra/gateway-server
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
    restart: on-failure

  stats-db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stats-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - stats-db-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  stats-server:
    build: ./stats/stats-service
    depends_on:
      stats-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
    restart: on-failure

  ewm-db:
    image: postgres:16.1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ewm-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - ewm-db-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  main-service:
    build: ./core/main-service
    depends_on:
      ewm-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-server:8761/eureka
    restart: on-failure

volumes:
  ewm-db-data:
  stats-db-data:
