CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment TEXT NOT NULL,
    date TIMESTAMP NOT NULL,
    author_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_comments_event_id ON comments(event_id);
CREATE INDEX IF NOT EXISTS idx_comments_author_id ON comments(author_id);
CREATE INDEX IF NOT EXISTS idx_comments_date ON comments(date);
