spring.application.name=event-service
server.port=0

spring.config.import=configserver:
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=10
spring.cloud.config.retry.initial-interval=2000
spring.cloud.config.retry.max-interval=10000
spring.cloud.config.retry.multiplier=1.5

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}

spring.cloud.openfeign.circuitbreaker.enabled=true

grpc.client.collector.address=discovery:///collector
grpc.client.collector.enableKeepAlive=true
grpc.client.collector.keepAliveWithoutCalls=true
grpc.client.collector.negotiationType=plaintext

grpc.client.analyzer.address=discovery:///analyzer
grpc.client.analyzer.enableKeepAlive=true
grpc.client.analyzer.keepAliveWithoutCalls=true
grpc.client.analyzer.negotiationType=plaintext
