spring.sql.init.mode=always

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5434}/ewm_analyzer
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:12345}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

analyzer.kafka.consumer.group-id.user-actions=analyzer-actions
analyzer.kafka.consumer.group-id.event-similarity=analyzer-similarity
analyzer.kafka.consumer.auto-offset-reset=earliest

analyzer.kafka.topic.user-actions=stats.user-actions.v1
analyzer.kafka.topic.event-similarity=stats.events-similarity.v1
