spring.cloud.gateway.routes[0].id=main-service-events
spring.cloud.gateway.routes[0].uri=lb://main-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/events/**

spring.cloud.gateway.routes[1].id=main-service-categories
spring.cloud.gateway.routes[1].uri=lb://main-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/categories/**

spring.cloud.gateway.routes[2].id=main-service-compilations
spring.cloud.gateway.routes[2].uri=lb://main-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/compilations/**

spring.cloud.gateway.routes[3].id=main-service-users
spring.cloud.gateway.routes[3].uri=lb://main-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/users/**

spring.cloud.gateway.routes[4].id=main-service-admin
spring.cloud.gateway.routes[4].uri=lb://main-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/admin/**
